### PR TITLE
Highlight / UnHighlight elements (new feature)

### PR DESCRIPTION
**Pull request by 6DiegoDiego9**
Added element highlighting features with 3 methods:
- WebElement.Highlight
- WebElement.UnHighlight
- (same 2 for WebElements)
- WebDriver.SetHightlightFoundElems  (one-time switch)

Examples of usage:
```
Sub test()
    Dim driver As New WebDriver
    Dim elem1 As WebElement, elem2 As WebElement
    Dim elems1 As WebElements, elems2 As WebElements
    With driver
        .StartEdge
        .OpenBrowser
        .NavigateTo "http://www.google.com"
        
        'automatically highlight every last found element(s):
        .SetHightlightFoundElems True
        Set elems1 = .FindElementsByXPath("//div[1]/ul/li")
        .Wait   'waits just to better enjoy the effects in this example 
        Set elems2 = .FindElementsByXPath("//div[2]/ul/li")
        .Wait
        Set elem1 = .FindElementByCssSelector("#W0wltc > div")
        .Wait
        Set elem2 = .FindElementByCssSelector("#L2AGLb > div")
        .Wait
        .SetHightlightFoundElems False
        
        'highlight specified elements (all arguments optional):
        elems1.Highlight borderColor:=Magenta
        .Wait
        elems2.Highlight borderColor:=Blue, UnHighlightLast:=False
        .Wait
        elem1.Highlight borderColor:=Cyan
        .Wait
        elem2.Highlight borderColor:=Green
        .Wait

        Stop
        .Shutdown
    End With
End Sub
```

### CODE REVIEW

**Comment by GCuser99** [comment]
Thx @6DiegoDiego9, I'm traveling now but will have a chance to take a look by the weekend or soon after...

**Comment by 6DiegoDiego9** [comment]
I forgot to mention that I made the methods chainable, for example:

`elem1.Highlight.Click  'highlight then click the element`

**Comment by GCuser99** [comment]
Thanks for the new functions - very cool. 

I couldn't get the test sub you provided to work - it failed on the first css selector (could not find element). Also, I will make the following modification on my next pull to your SetHighlight method of the WebDriver class to prevent "key already exists" error:
```
        For Each element In elements
            If Not lastElems.IsMember(element) Then lastElems.Add element
        Next element
```

**Comment by 6DiegoDiego9** [comment]
Thanks for the bug fix! :)

About my test sub, oh I now remember that some of your tests that go to https://www.google.com did not (and still don't) work to me so now I'm sure that all this must be caused by the fact that on my PCs if I open Google with a new profile as well as in InPrivate (Edge) or Incognito (Chrome) mode I get [this popup](https://iili.io/PvJoBe.jpg) asking me to accept how cookies and data are used by Google.
I suspect that this popup is shown to me because it detects that I'm under European  (or Italian) privacy laws.

My test highlighted elements on this popup.
Your solution with a saved string bypasses the problem though :)

Not sure about what to do with all the other involved tests. Not a priority issue, anyway, since the test scripts were easy and readable enough for me to understand that I had to (manually) close the popup for the script to continue as expected.

**Comment by GCuser99** [comment]
Hmmm - this is a very annoying problem. And a quick web search reveals no clean solution like setting a preference in capabilities. I've already experienced the test scripts breaking due to changes made on the server side (www.guru99.com being one of the problem sites). But never expected google.com to be a problem - that's unfortunate. Over time, I will chip away at creating more robust test examples, like using the html file snippets when applicable.

**Comment by GCuser99** [comment]
@6DiegoDiego9, I was thinking to change the test examples that use www.Google.com to https://www.wikipedia.org/ - are you able to navigate to that website without problem?

**Comment by 6DiegoDiego9** [comment]
I opened it InPrivate and I got [this resulting page](https://pasteboard.co/tvN2H6MVKZOY.png) that seems localized prioritizing my native language (Italian) :(

This is [bing.com](https://pasteboard.co/qE0kTdCS7aC3.png) instead.

**Comment by GCuser99** [comment]
I think the wiki main page might work. In the following example, we could pick phrases or places that are language independent...
```
Sub test_sendkeys()
    Dim driver As SeleniumVBA.WebDriver
    Dim keys As SeleniumVBA.WebKeyboard
    Dim keySeq As String
    
    Set driver = SeleniumVBA.New_WebDriver
    Set keys = SeleniumVBA.New_WebKeyboard

    driver.StartEdge
    
    driver.OpenBrowser
    
    driver.NavigateTo "https://www.wikipedia.org/"
    driver.Wait 1000
    
    keySeq = "Veropna" & keys.LeftKey & keys.LeftKey & keys.LeftKey & keys.DeleteKey & keys.ReturnKey
    
    driver.FindElement(by.ID, "searchInput").SendKeys keySeq

    driver.Wait 1000
    
    driver.CloseBrowser
    driver.Shutdown
End Sub
```

**Comment by 6DiegoDiego9** [comment]
It works :)
Yes we could use it, just remembering that the order of languages vary by localization.

**Pull request merged**
